# Generated by Django 5.0.6 on 2024-07-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_avatar_alter_customuser_discord_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='discord_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
